### PR TITLE
Fix most warnings

### PR DESCRIPTION
**Pull request by jfinkhaeuser**
I'm constantly distracted by the warnings during development. This only makes sense after #24 is merged, so keep open for now.

### CODE REVIEW

**Comment by mnaamani** [comment]
The line at the top of most of the files has been kept:

`#![cfg_attr(not(feature = "std"), no_std)]`

The compiler is giving us a warning about not using `no_std` attribute anywhere.

I understand that its important when compiling the runtime to WASM that we have to disable any crate from using `std` feature. This line is obviously related, but I don't understand it properly to know if it is safe to remove. Any ideas?

**Comment by mnaamani** [comment]
Great that you took the time to get rid of all these warnings. ❤️ 
LGTM (didn't review the storage implementation)

**Comment by jfinkhaeuser** [comment]
> The line at the top of most of the files has been kept:
> 
> `#![cfg_attr(not(feature = "std"), no_std)]`
> 
> The compiler is giving us a warning about not using `no_std` attribute anywhere.
> 
> I understand that its important when compiling the runtime to WASM that we have to disable any crate from using `std` feature. This line is obviously related, but I don't understand it properly to know if it is safe to remove. Any ideas?

I *think* it means we should have this only in `src/lib.rs`, but would have to try it out.

**Comment by mnaamani** [comment]
oh right, that it only makes sense to place it in the crate root?

**Comment by mnaamani** [comment]
This is just a nuance, but technically the title of the PR is fix warnings (we are not silencing them by setting a compiler flag) which is a good thing :)
I wonder if we should have a commit hook to prevent committing code with warnings? Perhaps for another time.

**Comment by jfinkhaeuser** [comment]
> oh right, that it only makes sense to place it in the crate root?

I read it that way, but I'm not sure.

**Comment by jfinkhaeuser** [comment]
There's also at least one warning I didn't do anything about, but you'll see that soonish, I think.

**Pull request merged**
